@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!theme C4_OneIdentity from https://raw.githubusercontent.com/mpierson/oi-doc-generators/refs/heads/main/plantuml
!include https://raw.githubusercontent.com/mpierson/oi-doc-generators/refs/heads/main/plantuml/ois-sprites.puml

HIDE_STEREOTYPE()

UpdateSystemBoundaryStyle($bgColor="white")
UpdateRelStyle($COLOR_OI_BLACK, $COLOR_OI_LOBLOLLY)


AddComponentTag("OneIM_Deploy_DB", $bgColor=$COLOR_OI_JAFFA, $fontColor="white", $borderColor="$COLOR_OI_GRAY" , $sprite="database_server,scale=0.6,color=white"  )
AddComponentTag("OneIM_Deploy_JS", $bgColor=$COLOR_OI_NEPAL, $fontColor="white" , $sprite="ICON_OneIM,scale=0.4,color=white" )
AddComponentTag("OneIM_Deploy_WS", $bgColor=$COLOR_OI_MONTE_CARLO, $fontColor="white" , $sprite="ICON_OneIM,scale=0.4,color=white" )
AddComponentTag("OneIM_Deploy_AS", $bgColor=$COLOR_OI_BLUE_LAGOON, $fontColor="white" , $sprite="ICON_OneIM,scale=0.4,color=white" )
AddComponentTag("OneIM_Deploy_Tools", $bgColor=$COLOR_OI_LOBLOLLY, $fontColor="white" , $sprite="ICON_OneIM,scale=0.4,color=white" )

AddComponentTag("AR_Deploy_DB", $bgColor=$COLOR_OI_JAFFA, $fontColor="white", $borderColor="$COLOR_OI_GRAY" , $sprite="database_server,scale=0.6,color=white"  )
AddComponentTag("AR_Deploy_AS", $bgColor=$COLOR_OI_JACARTA, $fontColor="white" , $sprite="ICON_ARS,scale=0.4,color=white" )



AddComponentTag("SG_Deploy_S4SUDO", $bgColor=$COLOR_OI_BLUE_LAGOON, $fontColor="white" , $sprite="ICON_S4SUDO,scale=0.4,color=white" )
AddComponentTag("SG_Deploy_SAS", $bgColor=$COLOR_OI_PEAR, $fontColor="white" , $sprite="ICON_SAS,scale=0.4,color=white" )
AddComponentTag("SG_Deploy_SPP", $bgColor=$COLOR_OI_MONTE_CARLO, $fontColor="white" , $sprite="ICON_SPP,scale=0.4,color=white" )
AddComponentTag("SG_Deploy_SPS", $bgColor=$COLOR_OI_NEPAL, $fontColor="white" , $sprite="ICON_SPS,scale=0.4,color=white" )

AddComponentTag("StarlingConnect_Connector", $bgColor=$COLOR_OI_BLUE, $fontColor="white" , $sprite="ICON_Starling,scale=0.4,color=white" )

AddComponentTag("Deploy_ActiveDirectory", $bgColor="#0078D4", $fontColor=white, $sprite="active_directory,scale=0.7,color=white")
AddComponentTag("Deploy_Azure", $bgColor="#0078D4", $fontColor=white, $sprite="azure,scale=0.7,color=white")
AddComponentTag("Deploy_AzureActiveDirectory", $bgColor="#0078D4", $fontColor=white, $sprite="AzureActiveDirectory,scale=0.7,color=white")
AddComponentTag("Deploy_AzureD365", $bgColor="#0078D4", $fontColor=white, $sprite="mdiMicrosoftDynamics365,scale=0.7,color=white")

AddComponentTag("Deploy_API", $bgColor="#0078D4", $fontColor=white, $sprite="cogs,scale=0.7,color=white")

AddComponentTag("Deploy_Workday", $bgColor="#0F2E66", $fontColor=white, $sprite="cogs,scale=0.7,color=white")
AddComponentTag("Deploy_UKG", $bgColor="#005151", $fontColor=white, $sprite="cogs,scale=0.7,color=white")
AddComponentTag("Deploy_Splunk", $bgColor="#0C1724", $fontColor=white, $sprite="ICON_Splunk,scale=0.3,color=white")

AddNodeTag("Deploy_Area",$bgColor=white, $fontColor=$COLOR_OI_GRAY)
AddNodeTag("Deploy_SubArea",$bgColor="#EDEDED", $fontColor=$COLOR_OI_GRAY)
AddNodeTag("Deploy_Infrastructure",$bgColor=$COLOR_OI_GRAY, $fontColor=white)
 


@enduml
