!$THEME = "C4_OneIdentity"

!$COLOR_OI_BLACK    = "#162c36"
!$COLOR_OI_BLUE     = "#04aada"
!$COLOR_OI_BLUEx    = "#09acd9"
!$COLOR_OI_GRAY     = "#40535d"

' secondary colours
!$COLOR_OI_JACARTA      = "#3f2c69"
!$COLOR_OI_MONTE_CARLO  = "#77c8b3"
!$COLOR_OI_JAFFA        = "#ee8a54"
!$COLOR_OI_NEPAL        = "#82a7c5"

' tertiary colours
!$COLOR_OI_PEAR         = "#cddb28"
!$COLOR_OI_LOBLOLLY     = "#cad4d7"
!$COLOR_OI_BLUE_LAGOON  = "#00969f"
!$COLOR_QUEST_ORANGE    = "#fb4f14"


' old color scheme
!$COLOR_OI_GREEN = "#afcc9e"
!$COLOR_OI_BROWN = "#c8b483"
!$COLOR_OI_ORANGE = "#f79431"
!$COLOR_OI_RED = "#f05640"
!$COLOR_OI_PINK = "#f4b3b2"
!$COLOR_OI_LIGHT_BLUE = "#9dcdda"
!$COLOR_OI_YELLOW = "#f0df3f"
!$COLOR_OI_DARK_GREEN = "#a9c750"


!$ELEMENT_FONT_COLOR ?= $COLOR_OI_BLACK
!$ELEMENT_FONT_NAME ?= "DejaVu"

!$PERSON_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$PERSON_BG_COLOR ?= $COLOR_OI_BLUE
!$PERSON_BORDER_COLOR ?= $COLOR_OI_BLACK
!$EXTERNAL_PERSON_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$EXTERNAL_PERSON_BG_COLOR ?= $COLOR_OI_BLUE
!$EXTERNAL_PERSON_BORDER_COLOR ?= $COLOR_OI_BLACK

!$SYSTEM_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$SYSTEM_BG_COLOR ?= $COLOR_OI_BROWN
!$SYSTEM_BORDER_COLOR ?= $COLOR_OI_BLACK
!$EXTERNAL_SYSTEM_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$EXTERNAL_SYSTEM_BG_COLOR ?= "#999999" 
!$EXTERNAL_SYSTEM_BORDER_COLOR ?= "#8A8A8A" 

!$CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$CONTAINER_BG_COLOR ?= "white" 
!$CONTAINER_BORDER_COLOR ?= "#3C7FC0" 
!$EXTERNAL_CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR 
!$EXTERNAL_CONTAINER_BG_COLOR ?= "#B3B3B3" 
!$EXTERNAL_CONTAINER_BORDER_COLOR ?= "#A6A6A6" 

!$COMPONENT_FONT_COLOR ?= "#000000" 
!$COMPONENT_BG_COLOR ?= "#85BBF0" 
!$COMPONENT_BORDER_COLOR ?= "#78A8D8" 
!$EXTERNAL_COMPONENT_FONT_COLOR ?= $COMPONENT_FONT_COLOR 
!$EXTERNAL_COMPONENT_BG_COLOR ?= "#CCCCCC" 
!$EXTERNAL_COMPONENT_BORDER_COLOR ?= "#BFBFBF" 


!$ARROW_COLOR ?= $COLOR_OI_GRAY
!$ARROW_FONT_COLOR ?= $COLOR_OI_GRAY

